name: decentralized_watchtower_goerli
author: valory
version: 0.1.0
description: A set of agents implementing the Decentralized Watchtower.
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint:
  README.md: bafybeiblcg3qti2cyz4ytufdkmqzcm6svbo5cwgsu2srjovvljdi35iz6i
fingerprint_ignore_patterns: []
agent: valory/keep3r_bot:0.1.0:bafybeig5bv6o2bctqrh5yrdmusjuo5t2affayfjcln5e7jbzzqljn4ttue
number_of_agents: 4
deployment:
  tendermint:
    ports:
      0:
        26656: 26656
      1:
        26666: 26656
      2:
        26676: 26656
      3:
        26686: 26656
---
public_id: valory/keep3r_abci:0.1.0
