agent_name: decentralized_watchtower
author: valory
version: 0.1.0
license: Apache-2.0
description: A decentralized watchtower agent.
aea_version: '>=1.0.0, <2.0.0'
fingerprint:
  __init__.py: bafybeihmmm754t5uz7payh7jwlddckfk4a7sjkovneffauhiu57lwjvwky
  tests/__init__.py: bafybeih43i6ohjc4t4yhhtdpznk5h3lmrkjpsdbkjhru34eq2xvk7lbjpm
  tests/helpers/__init__.py: bafybeiaeembrwmubrocabnhtxubrufvyq74k4lwwcihkktqpn63jqrdudi
  tests/helpers/constants.py: bafybeih6o7k2ulapbgyptmxc23rutaa7j3bk5gzlshe5svawjop42s7l5e
  tests/helpers/data/json_server/data.json: bafybeif46j5zkplndkezilq2fxytyqd3zwe6xr52pkjwh7yulu5234f6em
  tests/helpers/docker.py: bafybeibtyhtiny3lw67rzvlkvprcnsopxvwkisn3q4ooll2wn557ipad3y
  tests/helpers/fixtures.py: bafybeihxzhlr3tbwsoe3y3zczivoxbbkvccvtct4c6rff6qhfentcyl32i
  tests/test_agents/__init__.py: bafybeicmv3jjcqcdnmubfmrgdgeyic3nkm77z4mutsyuo34hpddwupofre
  tests/test_agents/base.py: bafybeict5wlx6k2rdyhpo6otvthwticefisfh3el6so5tyxmjufry5hegq
  tests/test_agents/test_decentralized_watchtower.py: bafybeiackbxkmxhmpnfe5kvtfksq3lktaa5ebtwruowkzu72aav54ip2ci
fingerprint_ignore_patterns: []
connections:
- fetchai/http_server:0.22.0:bafybeihp5umafxzx45aad5pj7s3343se2wjkgnbirt4pybrape22swm6de
- valory/abci:0.1.0:bafybeicasheudousm2unmh5qmy5n3qdq5hmkg2j42fxfm2crxmgq3nzjkq
- valory/http_client:0.23.0:bafybeieoeuy4brzimtnubmokwirhrx27ezls6cdnl5qik4rkykfle3nn2y
- valory/ipfs:0.1.0:bafybeiau32pzy55ta6ugl2bebevlxudal6pnlfomhplfm5mph6reaw3krq
- valory/ledger:0.19.0:bafybeigfoz7d7si7s4jehvloq2zmiiocpbxcaathl3bxkyarxoerxq7g3a
- valory/p2p_libp2p_client:0.1.0:bafybeihdnfdth3qgltefgrem7xyi4b3ejzaz67xglm2hbma2rfvpl2annq
- valory/websocket_client:0.1.0:bafybeicz53kzs5uvyiod2azntl76zwgmpgr22ven4wl5fnwt2m546j3wsu
contracts:
- valory/composable_cow:0.1.0:bafybeifsi2mwo3r4qh5oqccpbc47llz3tkxyodj7gtrnrm5z4bekv63che
- valory/gnosis_safe:0.1.0:bafybeigvqg4lapdaa23dpc3pv67rdptdhey6e435mxqsw2gb2u74yw4yei
- valory/gnosis_safe_proxy_factory:0.1.0:bafybeie4iivrxcd5dcwzj3y2t66mc5mdvtsuqu426gk2kcdc6fxbki6neu
- valory/multisend:0.1.0:bafybeie7m7pjbnw7cccpbvmbgkut24dtlt4cgvug3tbac7gej37xvwbv3a
- valory/service_registry:0.1.0:bafybeif6x4zvsokwcetbrjdb4uyv4l3pqx756cg2ohv2zgcky5yuiwuqvi
protocols:
- open_aea/signing:1.0.0:bafybeifuxs7gdg2okbn7uofymenjlmnih2wxwkym44lsgwmklgwuckxm2m
- valory/abci:0.1.0:bafybeigootsvqpk6th5xpdtzanxum3earifrrezfyhylfrit7yvqdrtgpe
- valory/acn:1.1.0:bafybeiapa5ilsobggnspoqhspftwolrx52udrwmaxdxgrk26heuvl4oooa
- valory/contract_api:1.0.0:bafybeiasywsvax45qmugus5kxogejj66c5taen27h4voriodz7rgushtqa
- valory/default:1.0.0:bafybeiecmut3235aen7wxukllv424f3dysvvlgfmn562kzdunc5hdj3hxu
- valory/http:1.0.0:bafybeia5bxdua2i6chw6pg47bvoljzcpuqxzy4rdrorbdmcbnwmnfdobtu
- valory/ipfs:0.1.0:bafybeibjzhsengtxfofqpxy6syamplevp35obemwfp4c5lhag3v2bvgysa
- valory/ledger_api:1.0.0:bafybeigsvceac33asd6ecbqev34meyyjwu3rangenv6xp5rkxyz4krvcby
- valory/tendermint:0.1.0:bafybeidjqmwvgi4rqgp65tbkhmi45fwn2odr5ecezw6q47hwitsgyw4jpa
skills:
- valory/abstract_abci:0.1.0:bafybeicg7dv7cff34nv2k2z47c4yp4kddsxp3wozonzow6tnvfvwndz3cy
- valory/abstract_round_abci:0.1.0:bafybeigxjcci53vwytymzlhr37436yvenh7jup4astrn7dgyixo24aq2pq
- valory/cow_orders_abci:0.1.0:bafybeiddlvxmgg2px7cgo24lnrwwha62udfjcok6p7whhw6ojj3iag7zzi
- valory/decentralized_watchtower_abci:0.1.0:bafybeiamlvpuzaoaaxvhzqgyio3sx54vy2xvmhkpftltuqjfyewwog3tyq
- valory/order_monitoring:0.1.0:bafybeihhtihm7ialzzqa3jiqwcjllren7rkvmxk5oexwlmrphfaevfwdva
- valory/registration_abci:0.1.0:bafybeibc4kczqbh23sc6tufrzn3axmhp3vjav7fa3u6cnpvolrbbc2fd7i
- valory/reset_pause_abci:0.1.0:bafybeid445uy6wwvugf3byzl7r73c7teu6xr5ezxb4h7cxbenghg3copvy
- valory/termination_abci:0.1.0:bafybeiguy7pkrcptg6c754ioig4mlkr7truccym3fpv6jwpjx2tmpdbzhi
- valory/transaction_settlement_abci:0.1.0:bafybeidpsnguxizkpihtkqzojr3em7yy7c6qc7gxpbh5vglmwws5wke7bi
default_ledger: ethereum
required_ledgers:
- ethereum
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  version: 1
  disable_existing_loggers: false
  formatters:
    standard:
      format: '[%(asctime)s] [%(levelname)s] %(message)s'
  handlers:
    logfile:
      class: logging.FileHandler
      formatter: standard
      filename: ${LOG_FILE:str:log.txt}
      level: INFO
    console:
      class: logging.StreamHandler
      formatter: standard
      stream: ext://sys.stdout
  loggers:
    aea:
      handlers:
      - logfile
      - console
      propagate: false
dependencies:
  open-aea-ledger-ethereum: {}
default_connection: null
---
public_id: valory/abci:0.1.0
type: connection
config:
  target_skill_id: valory/decentralized_watchtower_abci:0.1.0
  host: ${str:localhost}
  port: ${int:26658}
  use_tendermint: ${bool:false}
---
public_id: valory/p2p_libp2p_client:0.1.0
type: connection
config:
  nodes:
  - uri: ${str:acn.staging.autonolas.tech:9005}
    public_key: ${str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
cert_requests:
- identifier: acn
  ledger_id: ethereum
  message_format: '{public_key}'
  not_after: '2023-01-01'
  not_before: '2022-01-01'
  public_key: ${str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
  save_path: .certs/acn_cosmos_11000.txt
is_abstract: false
---
public_id: valory/decentralized_watchtower_abci:0.1.0
type: skill
models:
  params:
    args:
      cow_api_url: ${str:https://api.cow.fi/mainnet}
      cleanup_history_depth: 1
      setup:
        safe_contract_address: ${str:0x0000000000000000000000000000000000000000}
        all_participants: ${list:["0x0000000000000000000000000000000000000000"]}
        consensus_threshold: ${int:null}
      drand_public_key: 868f005eb8e6e4ca0a47c8a77ceaa5309a47978a7c71bc5cce96366b5d7a569937c529eeda66c7293784a9402801af31
      finalize_timeout: 60.0
      history_check_timeout: 1205
      keeper_allowed_retries: 3
      keeper_timeout: 30.0
      max_healthcheck: 120
      reset_pause_duration: 300
      on_chain_service_id: ${int:1}
      reset_tendermint_after: 60
      retry_attempts: 400
      retry_timeout: 3
      round_timeout_seconds: 120.0
      service_id: decentralized_watchtower
      service_registry_address: ${str:0x48b6af7B12C71f09e2fC8aF4855De4Ff54e775cA}
      sleep_time: 1
      share_tm_config_on_startup: ${bool:false}
      tendermint_check_sleep_delay: 3
      tendermint_max_retries: 5
      tendermint_url: ${str:http://localhost:26657}
      tendermint_p2p_url: ${str:localhost:26656}
      tendermint_com_url: ${str:http://localhost:8080}
      use_termination: ${bool:false}
      validate_timeout: 1205
---
public_id: valory/ledger:0.19.0
type: connection
config:
  ledger_apis:
    ethereum:
      address: ${str:http://localhost:8545}
      chain_id: ${int:31337}
      poa_chain: ${bool:false}
      default_gas_price_strategy: ${str:eip1559}
---
public_id: valory/websocket_client:0.1.0:bafybeicz53kzs5uvyiod2azntl76zwgmpgr22ven4wl5fnwt2m546j3wsu
type: connection
config:
  endpoint: ${str:ws://localhost:8545}
  target_skill_id: valory/order_monitoring:0.1.0
---
public_id: valory/order_monitoring:0.1.0:bafybeiby5ajjc7a3m2uq73d2pprx6enqt4ghfcq2gkmrtsr75e4d4napi4
type: skill
behaviours:
  subscriptions:
    args:
      contracts: ${list:["0xFf82123dFB52ab75C417195c5fDB87630145ae81"]}
handlers:
  new_event:
    args:
      contract_to_monitor: ${str:0xFf82123dFB52ab75C417195c5fDB87630145ae81}
      websocket_provider: ${str:ws://localhost:8545}
models:
  params:
    args:
      use_polling: ${bool:false}
      composable_cow_address: ${str:0x9A676e781A523b5d0C0e43731313A708CB607508}
      event_topics: ${list:["0x2cceac5555b0ca45a3744ced542f54b56ad2eb45e521962372eef212a2cbf361"]}
---
public_id: fetchai/http_server:0.22.0:bafybeihp5umafxzx45aad5pj7s3343se2wjkgnbirt4pybrape22swm6de
type: connection
config:
  host: 0.0.0.0
  target_skill_id: valory/decentralized_watchtower_abci:0.1.0
